from __future__ import annotations

SAMPLING_RATE = 2000
EMG_CHANNELS = 8
BAUDRATE = 921600
SERIAL_TIMEOUT_SEC = 0.02
RECORDER_BATCH_SAMPLES = 200
DISPLAY_FPS = 30
SOFTWARE_NAME = "EMG Data Collection"

